Отрисуй меня полностью (часть 2)
htmlacademy-javascript/1961791-kekstagram-26 pull request #6
Opened 2022-07-12 13:40 UTC by KatieZuzukina

2022-07-14 21:06 UTC, Zakamsky requested changes
В целом очень хорошо, но нужно исправить удаление секции и ее перенос, пусть она остается просто скрытая. Иначе мы делаем слишком много манипуляций с домом и еще и не чистим обработчики.
А еще нужно конечно удалять обработчик клика и останавливать цикл.

2022-07-14 21:06 UTC, Zakamsky commented on js/util.js
> +function isEscapeKey(evt) {
просто что бы ты знала на будущее: стрелочная функция позволяет нам выполнить эту же логику в одну строку:
```js
const isEscapeKey = (evt) => evt.key === 'Escape';
```

2022-07-14 21:06 UTC, Zakamsky commented on js/thumbnail.js
> +    clone.querySelector('.picture__img').id = id;
Хорошее решение, но `id` добавляет лишние сущности в дом, сейчас более оптимальным считается использовать дата атрибуты. Устанавливаются и читаются они через метод `dataset`: 
```js
// record: 
element.dataset.id = id
// read: 
const id = document.querySelector('.element').dataset.id
```
Это тоже в качестве дополнительной информации

2022-07-14 21:06 UTC, Zakamsky commented on js/big-photo.js
> +  document.body.appendChild(photoFull);
у нас штмл уже есть в разметке, его не нужно никуда вставлять и не нужно перемещать, мы только класс там меняем - `'hidden'`

2022-07-14 21:06 UTC, Zakamsky commented on js/big-photo.js
> +    photoFull.remove();
Этот тоже лишнее, просто класс обратно повесить...
так мы удалили секцию, но слушатель на кнопке остался и висит в памяти мертвым грузом...

2022-07-14 21:06 UTC, Zakamsky commented on js/big-photo.js
> +    document.removeEventListener('keydown', addKeydownEscHandler);
отлично, еще бы слушатель с кнопки закрытия тоже убрать

2022-07-14 21:06 UTC, Zakamsky commented on js/big-photo.js
> +  const photoFull = document.querySelector('.big-picture:not(.hidden)');
в принципе мы его уже нашли этот элемент и он есть в области видимости модуля, т.ч. искать его повторно не нужно.

2022-07-14 21:06 UTC, Zakamsky commented on js/big-photo.js
> +  bigPhotoTemlate.querySelector('img').src = url;
тут немного непонятные мне манипуляции, если мы извлекаем данные из массива - я бы доверял только им - вдруг у нас будут разные урлы, для миниатюры и полного изображения?
Это не ошибка конечно, можно так оставить.

2022-07-14 21:06 UTC, Zakamsky commented on js/big-photo.js
> +  for (let i = 0; i < thumbnail.length; i++) {
В целом циклы плохи ничем, кроме случаев когда нам могут быть не нужны все элементы массива.
В этом случае когда мы найдем нужный элемент - цикл продолжится для всех пока они есть, а их могут быть тысячи.
тут нам по хорошему надо бы либо найти способ остановить цикл, например [break](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/break)

или использовать метод массива который вернет нужный элемент и остановит перебор.
например [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

код выглядел бы так:

```js
// находим нужный элемент:
const photo = thumbnail.find( item => item.id.toString() === event.target.id );

// втсавляем его данные в разметку
bigPhotoTemlate.querySelector('.likes-count').textContent = photo.likes;
bigPhotoTemlate.querySelector('.comments-count').textContent = photo.comments.length;
bigPhotoTemlate.querySelector('.social__caption').textContent = photo.description;
```

2022-07-15 01:29 UTC, merged

2022-07-19 17:14 UTC, KatieZuzukina commented on js/big-photo.js
> +  const photoFull = document.querySelector('.big-picture:not(.hidden)');
этого элемента нет в области видимости модуля